src/Coduo/PHPMatcher/Matcher/CallbackMatcher.php, tests/Coduo/PHPMatcher/Matcher/CallbackMatcherTest.php
I found a problem with CallbackMatcher - it was executed for strings representing internal function names, like sin.
There is a small fix, that prevents execution of callbackMatcher on non-objects.
=> CallbackMatcher should not be executed for internal function names

README.md, composer.json, src/Coduo/PHPMatcher/Matcher/Pattern/Expander/IsUrl.php, src/Coduo/PHPMatcher/Parser/ExpanderInitializer.php, tests/Coduo/PHPMatcher/Matcher/Pattern/Expander/IsUrlTest.php, tests/Coduo/PHPMatcher/MatcherTest.php
This adds an isUrl() expander with a test case. Like the isEmail() expander, upon which it is based, it handles validation using the PHP filter extension.
=> Add isUrl() pattern expander

README.md
`@double@` had been duplicated.
=> the Content had been duplicated.

README.md, src/Coduo/PHPMatcher/Matcher/Pattern/Expander/isEmpty.php, src/Coduo/PHPMatcher/Parser/ExpanderInitializer.php, tests/Coduo/PHPMatcher/Matcher/Pattern/Expander/isEmptyTest.php, tests/Coduo/PHPMatcher/MatcherTest.php
This PR add a `IsEmpty` expander.
Does I miss something ?
=> Add IsEmpty expander

README.md, src/Coduo/PHPMatcher/Matcher/Pattern/Expander/MatchRegex.php, src/Coduo/PHPMatcher/Parser/ExpanderInitializer.php, tests/Coduo/PHPMatcher/Matcher/Pattern/Expander/MatchRegexTest.php, tests/Coduo/PHPMatcher/MatcherTest.php
The Match expander allow to use regex.
=> Add Match expander

phpunit.xml.dist, tests/bootstrap.php
These are defaults anyway so there is no reason to clutter the config. There is also no need for the bootstrap file as it only includes the autoloader.
=> Remove redundant configurations

README.md, phpunit.xml.dist, src/PHPUnit/PHPMatcherAssertions.php, src/PHPUnit/PHPMatcherConstraint.php, src/PHPUnit/PHPMatcherTestCase.php, tests/PHPUnit/PHPMatcherAssertionsTest.php, tests/PHPUnit/PHPMatcherConstraintTest.php, tests/PHPUnit/PHPMatcherTestCaseTest.php
Should allow to do the following in phpunit tests:
```php
class FooTest extends \PHPUnit_Framework_TestCase
{
use PHPMatcherAssertions;
public function test_it_asserts_if_a_value_matches_the_pattern()
{
$this->assertMatchesPattern('@integer@', 'foo');
}
}
```
```
Failed asserting that 'foo' matches the pattern.
"foo" does not match "@integer@" pattern
```
For PHP 5.3 `PHPMatcherTestCase` is provided.
=> PHPUnit integration

composer.json
Hi,
This PR allow to install php-matcher on project depending on other lib-array2xml version.
I made the PR on 1.0 because the issue is on all branches
What do you think ?
=> Change openlss/lib-array2xml version to >= 0.0.9

src/Matcher/ArrayMatcher.php, src/Matcher/NullMatcher.php, tests/Matcher/ArrayMatcherTest.php, tests/Matcher/JsonMatcherTest.php
@norzechowicz code review please
=> #71 Null value matching problem

src/Factory/SimpleFactory.php, src/Matcher/OrMatcher.php, tests/Matcher/OrMatcherTest.php, tests/MatcherTest.php
@defrag @norzechowicz code review please
any advices welcome
=> #53 Added OR operator support

src/Lexer.php
This works around a bug in php 7.0.5, which reveals itself under specific circumstances, seemingly involving switch statements and assigning by reference.
closes #77
=> work around bug https://bugs.php.net/bug.php?id=71964

tests/MatcherTest.php
Regarding to issue reported in #82 
@norzechowicz ping
=> #82 Null not work correctly - added test case

README.md, src/Factory/SimpleFactory.php, src/Matcher/UuidMatcher.php, tests/Matcher/UuidMatcherTest.php, tests/MatcherTest.php
=> Added UUID matcher.

src/Matcher/UuidMatcher.php, tests/Matcher/UuidMatcherTest.php
UUID have  [multiple versions](https://en.wikipedia.org/wiki/Universally_unique_identifier#Variants_and_versions]).
For example Mysql use [version 1](http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_uuid)
=> add support for all versions of UUID [1-5]

src/Matcher/ArrayMatcher.php, tests/Matcher/ArrayMatcherTest.php, tests/MatcherTest.php
fixes issue #72, by allowing @...@ to match none or more elements. Also added unit tests
=> Allow @...@ to match none or more elements

README.md, src/Matcher/ArrayMatcher.php, src/Matcher/Pattern/Expander/Contains.php, src/Matcher/Pattern/Expander/Count.php, src/Matcher/Pattern/Expander/EndsWith.php, src/Matcher/Pattern/Expander/GreaterThan.php, src/Matcher/Pattern/Expander/InArray.php, src/Matcher/Pattern/Expander/IsDateTime.php, src/Matcher/Pattern/Expander/IsEmail.php, src/Matcher/Pattern/Expander/IsEmpty.php, src/Matcher/Pattern/Expander/IsNotEmpty.php, src/Matcher/Pattern/Expander/IsUrl.php, src/Matcher/Pattern/Expander/LowerThan.php, src/Matcher/Pattern/Expander/MatchRegex.php, src/Matcher/Pattern/Expander/OneOf.php, src/Matcher/Pattern/Expander/Optional.php, src/Matcher/Pattern/Expander/StartsWith.php, src/Matcher/Pattern/Pattern.php, src/Matcher/Pattern/PatternExpander.php, src/Matcher/Pattern/TypePattern.php, src/Parser.php, src/Parser/ExpanderInitializer.php, tests/Matcher/Pattern/Expander/OptionalTest.php, tests/Matcher/Pattern/PatternTest.php, tests/Matcher/Pattern/RegexConverterTest.php, tests/MatcherTest.php
>useless for scalar matchers
> should resolve #93 
> `optional()` expander is also available for `ArrayMatcher` due to `JsonMatcher` & `XmlMatcher` is created using `ArrayMatcher`. There's no a simple way to exclude `optional()` expander functionality from `ArrayMatcher` 
-----
~~Also return type declaration was added for for *Pattern inteface*.~~
=> Allow to mark JSON properties & XML nodes as optional

.travis.yml, README.md, src/Matcher/ArrayMatcher.php, src/Matcher/Pattern/Expander/Contains.php, src/Matcher/Pattern/Expander/Count.php, src/Matcher/Pattern/Expander/EndsWith.php, src/Matcher/Pattern/Expander/GreaterThan.php, src/Matcher/Pattern/Expander/InArray.php, src/Matcher/Pattern/Expander/IsDateTime.php, src/Matcher/Pattern/Expander/IsEmail.php, src/Matcher/Pattern/Expander/IsEmpty.php, src/Matcher/Pattern/Expander/IsNotEmpty.php, src/Matcher/Pattern/Expander/IsUrl.php, src/Matcher/Pattern/Expander/LowerThan.php, src/Matcher/Pattern/Expander/MatchRegex.php, src/Matcher/Pattern/Expander/OneOf.php, src/Matcher/Pattern/Expander/Optional.php, src/Matcher/Pattern/Expander/StartsWith.php, src/Matcher/Pattern/Pattern.php, src/Matcher/Pattern/PatternExpander.php, src/Matcher/Pattern/TypePattern.php, src/Parser/ExpanderInitializer.php, tests/Matcher/Pattern/Expander/IsNotEmptyTest.php, tests/Matcher/Pattern/Expander/OptionalTest.php, tests/Matcher/Pattern/PatternTest.php, tests/MatcherTest.php
* Add optional expander definition
* Add hasExpander method for Pattern
* Allow mark JSON properties & xml nodes as optional
* Use intuitive matcher type definition in Xml test stock qty node definition
* Add information about optional Expander to README
* Remove return type declaration
* Catch PHPMatcher Exception when parsing pattern for optional values
* Add getName to PatternExpander interface
* Remove unncessary ExpanderInitializer dependency in TypePattern
* Use constants for expander name instead of method
* Redeclare $expanderDefinitions using constants
* Add static is($name) method to PatternExpander interface
=> Allow to mark JSON properties & XML nodes as optional (#102)

README.md, src/Matcher/Pattern/Expander/Repeat.php, src/Parser/ExpanderInitializer.php, tests/Matcher/Pattern/Expander/RepeatTest.php
Add "repeat" requested feature in:
https://github.com/coduo/php-matcher/issues/35
And also in:
https://github.com/coduo/php-matcher/issues/21
Feel free to comment, give advice.
I want to merge on 2.3 because I want to stick with PHP 5.6 not 7.
=> 2.3 - Add repeat expander feature

src/Matcher/Pattern/Expander/Repeat.php, tests/Matcher/Pattern/Expander/RepeatTest.php
=> [3.0] Fix bad encoding in Repeat expander

src/Matcher/OrMatcher.php, tests/Matcher/OrMatcherTest.php
`OR` matcher was added to `2.x` version. So the same PR must be added to `2.x` branches as well.
=> Trim whitespaces around the matchers after `OR` splitting

src/Parser.php, tests/MatcherTest.php
Using value like:
`{"name": "123"}`
for pattern: 
`{"name": ""}`
results in:
```
TypeError: Argument 1 passed to Coduo\PHPMatcher\Parser::unexpectedSyntaxError() must be of the type array, null given, called in /home/jacek/workspace/php-matcher/src/Parser.php on line 66
/home/jacek/workspace/php-matcher/src/Parser.php:252
/home/jacek/workspace/php-matcher/src/Parser.php:66
/home/jacek/workspace/php-matcher/src/Parser.php:54
/home/jacek/workspace/php-matcher/src/Parser.php:29
/home/jacek/workspace/php-matcher/src/Matcher/StringMatcher.php:43
/home/jacek/workspace/php-matcher/src/Matcher/ChainMatcher.php:32
/home/jacek/workspace/php-matcher/src/Matcher/ChainMatcher.php:33
/home/jacek/workspace/php-matcher/src/Matcher/ArrayMatcher.php:165 …
```
=> Matcher fails when trying to use empty string as a pattern

src/PHPUnit/PHPMatcherConstraint.php
While using the PHPUnit test helper we get this error 
```
PHP Fatal error:  Declaration of Coduo\PHPMatcher\PHPUnit\PHPMatcherConstraint::additionalFailureDescription($other) must be compatible with PHPUnit\Framework\Constraint\Constraint::additionalFailureDescription($other): string in /home/vagrant/code/vendor/coduo/php-matcher/src/PHPUnit/PHPMatcherConstraint.php on line 11
2018-03-23T23:25:18+00:00 [critical] Fatal Compile Error: Declaration of Coduo\PHPMatcher\PHPUnit\PHPMatcherConstraint::additionalFailureDescription($other) must be compatible with PHPUnit\Framework\Constraint\Constraint::additionalFailureDescription($other): string
```
```
Fatal error: Declaration of Coduo\PHPMatcher\PHPUnit\PHPMatcherConstraint::additionalFailureDescription($other) must be compatible with …
```
=> Fix return type-hint

README.md, src/Matcher/Pattern/Expander/NotContains.php, tests/Matcher/Pattern/Expander/ContainsTest.php, tests/Matcher/Pattern/Expander/NotContainsTest.php
=> NotContains expander

src/Matcher/Pattern/RegexConverter.php, src/Matcher/UuidMatcher.php, tests/Matcher/TextMatcherTest.php
This PR resolves the #112 issue. It enables to use the `@uuid@` pattern with the `TextMatcher`.
This pattern is actually not supported : `Type pattern "@uuid@" is not supported by TextMatcher.`
After this patch, we can use : 
```
if (!PHPMatcher::match("/user/ebd1fb0e-45ae-11e8-842f-0ed5f89f718b/profile", "/user/@uuid@/profile", $error)) {
echo $error;
} else {
echo "Matched.";
}
```
=> Added UUID pattern support for the TextMatcher

README.md, src/Matcher/Pattern/Expander/IsIp.php, src/Parser/ExpanderInitializer.php, tests/Matcher/Pattern/Expander/IsIpTest.php, tests/MatcherTest.php
This PR adds an ``isIp()``pattern expander, it is based on the PHP filter extension.
This pattern checks IPv4 and IPv6 addresses within public, private and reserved range.
Example usage : 
``` 
if (!PHPMatcher::match("127.0.0.1", "@string@.isIp()", $error)) {
echo $error;
} else {
echo "Matched.";
}
```
=> Added isIp() pattern expander

README.md, src/Lexer.php, src/Matcher/ArrayMatcher.php, tests/LexerTest.php, tests/Matcher/ArrayMatcherTest.php, tests/Matcher/JsonMatcherTest.php
Array universal key `@*@` will match any key not presented in the pattern.
It works similarly to `@...@` but for key-value arrays.
It needs `"@*@": "@*@"` instead of just `@*@` or `@...@` to bypass JSON validation.
It solves problem described in #40 but it is more elastic than #39 and #132 as it allows both specifying value pattern (like `"@*@": @string@`) and place where additional keys are allowed. Also it is more obvious to guess what wildcard key does than learning about pattern modifiers.
=> Array universal key

.travis.yml, phpunit.xml.dist
- Remove `sudo: false` setting because the root privilege is disabled by default.
The reference is [here](https://docs.travis-ci.com/user/reference/trusty/#container-based-infrastructure).
- Remove the excluded files because the PHP will always be greater than `7.0` version now.
=> Enhance PHPUnit setting

src/PHPUnit/PHPMatcherConstraint.php
Fix `Error: Cannot call constructor` while using PHPUnit 8.
Constructor of `PHPUnit\Framework\Constraint\Constraint` was removed in PHPUnit 8 (https://github.com/sebastianbergmann/phpunit/issues/3060).
=> PHPUnit 8 compatibility

src/Matcher/Pattern/Expander/Repeat.php, src/Matcher/TextMatcher.php, tests/Matcher/JsonMatcherTest.php
=> Fix Repeat expander in JSON Context

composer.json
version 1 has been released:
https://github.com/nullivex/lib-array2xml/releases
This also allows php-matcher to be installed along side psalm:
https://github.com/vimeo/psalm/pull/1745
=> Require stable version of openlss/lib-array2xml

composer.json, src/PHPUnit/PHPMatcherConstraint.php
This would help debugging:
```
❯ bin/phpunit --testdox --filter testmytest
PHPUnit 7.5.14 by Sebastian Bergmann and contributors.
Coduo\PHPMatcher\Tests\PHPUnit\PHPMatcherAssertions
✘ Mytest
│
│ Failed asserting that '{"foo":"bar"}' matches the pattern.
│ "bar" does not match "@integer@".
│ --- Expected
│ +++ Actual
│ @@ @@
│  {
│ -    "foo": "@integer@"
│ +    "foo": "bar"
│  }
```
The code was taken from PhpUnit JSON string asserts with few changes.
=> Add PhpUnit rich diff for JSON string comparison

src/Matcher.php, src/Matcher/Matcher.php, src/Matcher/ValueMatcher.php, tests/Matcher/JsonMatcherTest.php, tests/MatcherTest.php
This should fix https://github.com/coduo/php-matcher/issues/156 I wasn't sure what was wrong there but @teklakct pointed out that matcher is returning error even if matching was successful. 
If we think about how matcher works internally it kind of make sense but it's definitely not expected behavior. This PR should fix it.
=> Do not return any error when matching was successful

src/Matcher/Pattern/Assert/Json.php, tests/Matcher/JsonMatcherTest.php
This PR makes possible to use new lines in json patterns. 
Below valid use case reported in #165 
{
"id": "@number@",
"name": "@string@",
"entries": "@array@.repeat({
\"id\": \"@number@\",
\"question\": \"@string@\",
\"answer\": \"@string@\",
\"os\": \"@*@\"
})"
}
=> Added possibility to use new lines in json patterns

README.md, src/Factory/MatcherFactory.php, src/Factory/SimpleFactory.php, src/Matcher/JsonMatcher.php, src/Matcher/JsonObjectMatcher.php, src/Matcher/Pattern/Assert/Json.php, src/Matcher/Pattern/Expander/Repeat.php, src/Matcher/XmlMatcher.php, src/PHPMatcher.php, src/PHPUnit/PHPMatcherConstraint.php, tests/EmptyPatternsTest.php, tests/ExpandersTest.php, tests/Matcher/JsonMatcherTest.php, tests/Matcher/OrMatcherTest.php, tests/Matcher/XmlMatcherTest.php, tests/OrMatcherTest.php
This PR goal is to increase verbosity of Json/XML matchers error messages. It also deprecates SimpleFactory in favor of MatcherFactory (simple was terrible name) and simplifies factory building process.
=>  Do not use anymore child matcher errors in Json/XML matchers

README.md, src/Factory/MatcherFactory.php, src/Matcher/JsonMatcher.php, src/Matcher/Pattern/Assert/Json.php, src/Matcher/Pattern/Expander/After.php, src/Matcher/Pattern/Expander/Before.php, src/Matcher/Pattern/Expander/Contains.php, src/Matcher/Pattern/Expander/Count.php, src/Matcher/Pattern/Expander/EndsWith.php, src/Matcher/Pattern/Expander/GreaterThan.php, src/Matcher/Pattern/Expander/InArray.php, src/Matcher/Pattern/Expander/IsDateTime.php, src/Matcher/Pattern/Expander/IsEmail.php, src/Matcher/Pattern/Expander/IsEmpty.php, src/Matcher/Pattern/Expander/IsIp.php, src/Matcher/Pattern/Expander/IsNotEmpty.php, src/Matcher/Pattern/Expander/IsUrl.php, src/Matcher/Pattern/Expander/LowerThan.php, src/Matcher/Pattern/Expander/Match.php, src/Matcher/Pattern/Expander/MatchRegex.php, src/Matcher/Pattern/Expander/NotContains.php, src/Matcher/Pattern/Expander/OneOf.php, src/Matcher/Pattern/Expander/Optional.php, src/Matcher/Pattern/Expander/Repeat.php, src/Matcher/Pattern/Expander/StartsWith.php, src/Matcher/Pattern/PatternExpander.php, src/Parser/ExpanderInitializer.php, tests/ExpandersTest.php
This is continuation of #101 originally created by @partikus that introduce extremely flexible `match` expander. It also closes #133 
All examples will return true:
```php
(new MatcherFactory())->match(
'{"image":null}',
'{"image":"@null@||@json@.match({\"url\":\"@string@.isUrl()\"})"}'
);
(new MatcherFactory())->match(
'{"image":{"url":"http://image.com"}}',
'{"image":"@null@||@json@.match({\"url\":\"@string@.isUrl()\"})"}'
);
(new MatcherFactory())->match(
'{"image":{"url":"http://image.com"}}',
'{"image":"@json@.oneOf(optional(), match({\"url\":\"@string@.isUrl()\"}) )"}'
);
```
=> Added match expander that allows to match nullable @json@ objects

src/Matcher/JsonMatcher.php, src/Matcher/Pattern/Assert/Json.php, tests/Matcher/JsonMatcherTest.php, tests/MatcherTest.php
Fixes #187, Json class was indeed broken but it wasn't affecting whole Matcher since it's not JsonMatcher that should be used to match `/foo/@uuid@/bar` but TextMatcher
=> Fixed json matcher when matching strings including other patterns

README.md
Fixed invalid json in part "Json matching with unbounded arrays and objects"
PR is against branch "3.1" because example  "Json matching with unbounded arrays and objects" was introduced there.
=>  README.md - fix example in "Json matching with unbounded arrays and objects" (3.1)

README.md, UPGRADE.md, composer.json, src/Backtrace.php, src/Factory.php, src/Factory/MatcherFactory.php, src/Factory/SimpleFactory.php, src/PHPMatcher.php, src/PHPUnit/PHPMatcherConstraint.php, tests/BacktraceTest.php, tests/EmptyPatternsTest.php, tests/ExpandersTest.php, tests/Factory/SimpleFactoryTest.php, tests/MatcherTest.php, tests/OrMatcherTest.php, tests/PHPUnit/PHPMatcherAssertionsTest.php, tests/PHPUnit/PHPMatcherConstraintTest.php, tests/PHPUnit/PHPMatcherTestCaseTest.php, tests/ParserSyntaxErrorTest.php
PHPMatcher API cleanup that replaces facade with regular class allowing to access last message/backtrace. 
**Creating Matcher:** 
```diff
-$factory = new MatcherFactory();
-$matcher = $factory->createMatcher();
+$matcher = new PHPMatcher();
```
**Using Matcher**
```diff
-PHPMatcher::match($value, $pattern, $error)
+$matcher = (new PHPMatcher())->match($value, $pattern);;
```
**Accessing last error/backtrace**
```diff
+$matcher = new PHPMatcher();
+$matcher->match($value, $pattern);
+echo $matcher->error();
+echo $matcher->backtrace();
```
=> Replaced PHPMatcher facade with implementation that makes possible to access backtrace
